plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'net.minecraftforge.gradle' version '7.0.20'
}

group = project.group
description = project.displayName
base.archivesName = project.name
version = '26.1.2-1.12.3'

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

minecraft {
    accessTransformer = true

    mappings channel: 'official', version: '26.1.2'

    runs {
        configureEach {
            workingDir.convention layout.projectDirectory.dir('run')

            systemProperty 'forge.logging.console.level', 'debug'
            systemProperty 'eventbus.api.strictRuntimeChecks', 'true'

            args "--mixin.config=presencefootsteps.mixin.json"
        }

        register('client')
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:26.1.2-64.0.1")
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'
}

tasks.named('jar', Jar) {
    manifest {
        attributes(['MixinConfigs': 'presencefootsteps.mixin.json'])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea.module { downloadJavadoc = downloadSources = true }
